spring:
  application:
    name: backend
  profiles:
    active: dev
  config:
    import: "optional:file:../.env[.properties]"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unihub_db}
    username: ${SPRING_DATASOURCE_USERNAME:unihub}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      password: ${SPRING_DATA_REDIS_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: ${JWT_EXPIRATION:86400000} # 1 day
  rate-limit:
    policies:
      - scope: IP
        endpoint: POST:/api/v1/registrations
        limit-value: 90
        window-seconds: 60
        algorithm: TOKEN_BUCKET
        enabled: true
      - scope: IP
        endpoint: POST:/api/v1/auth/login
        limit-value: 20
        window-seconds: 60
        algorithm: TOKEN_BUCKET
        enabled: true
      - scope: IP
        endpoint: GET:/api/v1/workshops
        limit-value: 300
        window-seconds: 60
        algorithm: TOKEN_BUCKET
        enabled: true
      - scope: USER
        endpoint: POST:/api/v1/payments
        limit-value: 3
        window-seconds: 10
        algorithm: TOKEN_BUCKET
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
